apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
data:
  lnd.conf: |
    {{- if eq .Values.chain "regtest" }}
      {{- tpl .Values.regtestConfig . | nindent 4 }}
    {{- end }}
    {{- .Values.baseConfig | nindent 4 }}
    {{- .Values.config | nindent 4 }}
