{
 "title": "Block Relay",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total CNode / Peer Memory (With TX Relay)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "bitcoin_peermem_cnode_withtx", "legendFormat": "__auto" },
    { "expr": "bitcoin_peermem_peer_withtx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total CNode / Peer Memory (No TX relay)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "bitcoin_peermem_cnode_notx", "legendFormat": "__auto" },
    { "expr": "bitcoin_peermem_peer_notx", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In / Out Connections Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "bitcoin_conn_in", "legendFormat": "__auto" },
    { "expr": "bitcoin_conn_out", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Used / Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "bitcoin_meminfo_total", "legendFormat": "__auto" },
    { "expr": "bitcoin_meminfo_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mempool size (#/tx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "bitcoin_mempool_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bytes Sent / Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "bitcoin_total_bytes_recv", "legendFormat": "__auto" },
    { "expr": "bitcoin_total_bytes_sent", "legendFormat": "__auto" }
   ]
  }
 ]
}